spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_batch
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  batch:
    job:
      names: ${job.name:NONE}
      jdbc:
        initialize-schema: ALWAYS
      jpa:
        show-sql: true